### ISSUE TITLE
Hello how to use ?

### ISSUE THREAD

**Issue by kingsalman99** [zyairelai/futures-hero#16]
![Screenshot_2021-04-16-07-14-14-84](https://user-images.githubusercontent.com/58569784/114954181-2e9f5e00-9e84-11eb-9143-c99264b08e35.jpg)

**Comment by kingsalman99** [comment]
why always Wait ,and no position

**Comment by zyairelai** [comment]
My code is not designed for gambling entry. 
It is designed for a waiting for uptrend or downtrend confirmation, and look for entry point.

If you want a bot that keep on buying and selling in seconds, perhaps my code is not a solution for you.
