### ISSUE TITLE
Error running on VPS

### ISSUE THREAD

**Issue by eugjr** [zyairelai/futures-hero#19]
Hello, I"m trying to run it on a VPS but get some Syntax errors in code:

````
/hero$ python run.py
Pair Name        :   BTCUSDT
Trade Quantity   :   0.001 BTC
Leverage         :   50
()
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    import strategy_hybrid
  File "/home/ubuntu/hero/strategy_hybrid.py", line 91
    print("4 HOUR YES") if hybrid.strong_trend(klines_4HOUR) == test_color else print("4 HOUR NO")
                                                                                    ^
SyntaxError: invalid syntax
```
`

**Comment by zyairelai** [comment]
![image](https://user-images.githubusercontent.com/49854907/137572744-d27b777e-fae1-4ed4-8073-3393b71b4ee9.png)

Output:
![Screenshot from 2021-10-16 11-50-58](https://user-images.githubusercontent.com/49854907/137572768-29ab560b-9a48-4743-84cb-70fb2268aa0d.png)

I had tested the similar syntax. There is no syntax in the error you sent me.  
Make sure you are running Python 3.7 or above
