### ISSUE TITLE
Strategie

### ISSUE THREAD

**Issue by htnlabs** [zyairelai/futures-hero#29]
Hello, is the strategy_hybrid.py strategy no longer available?

How can I get?

Congratulations for the good work. Inspiring

**Comment by zyairelai** [comment]
Hi @htnlabs 
It is no longer available as it is not compatible with current market trend, however, you can get it by searching the Github History (even though it is a mess but everything in the history was there)

**Comment by htnlabs** [comment]
> Hi @htnlabs It is no longer available as it is not compatible with current market trend, however, you can get it by searching the Github History (even though it is a mess but everything in the history was there)

Thanks. Congratulations
